# Generated by Django 3.2.8 on 2022-01-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='adult_count',
            new_name='person_count',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='child_count',
        ),
        migrations.AddField(
            model_name='booking',
            name='room_type',
            field=models.CharField(choices=[('std', 'Standard King Room'), ('sui', 'Deluxe Suite Room')], default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='stars',
            field=models.PositiveIntegerField(default=5),
            preserve_default=False,
        ),
    ]
